version: '3.4'

services:
  blazorapp.scrum:
    image: ${DOCKER_REGISTRY-}blazorappscrum
    build:
      context: .
      dockerfile: Scrum.Blazor/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    restart: always
    ports:
      - 7272:80
